const quotes = [
  "I'm not one of those complicated, mixed-up cats. I'm not looking for the secret to life... I just go on from day to day, taking what comes.",
  "With respect to the first of these obstacles, it has often been made a matter of grave complaint against Political Economists, that they confine their attention to Wealth, and disregard all consideration of Happiness or Virtue.",
  "Now the main areas of higher education that still enjoy considerable financial support from government are subjects like engineering and science and the research ringfence which is the basic minimum to protect Britain's scientific competitiveness.",
  "There's a schizoid streak within the family anyway so I dare say that I'm affected by that. The majority of the people in my family have been in some kind of mental institution, as for my brother he doesn't want to leave. He likes it very much.",
  "Masterpieces are not single and solitary births they are the outcome of many years of thinking in common, of thinking by the body of the people, so that the experience of the mass is behind the single voice.",
  "When you're young, you want to make every kind of film: musicals, Westerns, horror. Slowly you begin to hear your own voice. I hope people receive what I do as small, personal films that are somewhat contrarian about their main characters.",
  "Listening to my regular favourites - Mozart, Beethoven, Brahms and so on - I always feel, quite misguidedly, that nothing can be too bad if such beauty and brilliance exists in the world.",
  "The security of the United States, which is so dependent on having accurate and timely intelligence, is not a Republican or a Democratic issue.",
  "The Negro people of America... have cut our forests, tilled our fields, built our railroads, fought our battles, and in all of their trials they have manifested a simple faith, a grateful heart, a cheerful spirit, and an undivided loyalty .",
  "In a still hot morning, the tide went out and didn't come back in. This was not a spectacular event. The sea did not roll up like a scroll, like the sky in Revelations. It quietly withdrew.",
  "As I get older, all sorts of things become less funny. Once one has children, any cruelty involving children becomes far less amusing than when one was at the mercy of one's friends' and relatives' children.",
  "But now with the living conditions deteriorating, and with the sure knowledge that we are slated for destruction, we have been transformed into an implacable army of liberation.",
  "This avidity alone, of acquiring goods and possessions for ourselves and our nearest friends, is insatiable, perpetual, universal, and directly destructive of society.",
  "There is a lot of interest in the arts, music, theatre, filmmaking, engineering, architecture and software design. I think we have now transitioned the modern-day version of the entrepreneur into the creative economy.",
  "But as I was saying, from my experiences, I think men tend to be more timid in expressing their feelings for you. Regardless, I always prefer a friendship first and foremost.",
  "What is sure is that technological change is accelerating in all directions and, like children playing in a fountain, consumers are reveling in the experience.",
  "I am trying to make clear through my writing something which I believe: that biography- history in general- can be literature in the deepest and highest sense of that term.",
  "Violent behavior exists in one's psychological makeup much deeper than the level that receives information from television or movies.",
  "Part of the reason that the government's fear mongering is succeeding is because so many people are so ignorant, that it is easier for government to frighten people in submission.",
  "I'm kind of a failure. I mean, I'll be honest. I'm successful in that I'm getting to work on great stuff, but I think I'm a failure in all the personal stuff that is most important to me.",
  "There is no glory in war, yet from the blackness of its history, there emerge vivid colours of human character and courage. Those who risked their lives to help their friends.",
  "If I die a violent death, as some fear and a few are plotting, I know that the violence will be in the thought and the action of the assassins, not in my dying.",
  "In addition to this, they already have a fuel cell car on the road in Japan. It is subsidized from within the corporation because they are still at a high cost.",
  "I believe that being successful means having a balance of success stories across the many areas of your life. You can't truly be considered successful in your business life if your home life is in shambles.",
  "I am a beneficiary of the American people's generosity, and I hope we can have comprehensive immigration legislation that allows this country to continue to be enriched by those who were not born here.",
  "You can't possibly fathom the ins and outs of a prepubescent beauty treatment until you've felt the strange but exhilarating tingle of a cottage-cheese-and-Pop-Rocks facial.",
  "Fear may very well be a caveman fear of the predator, of the giant lizard chasing them - maybe that's what Steven Spielberg connects with so well in Lost World.",
  "Believe me, I understand the need for easy and speedy. After a 12-hour day of shooting 'Chopped,' say, I'm talking stir-fry, spaghetti, heck, peanut-butter sandwiches. But that's not about the joy of food. That's survival.",
  "The hope of the nation which throughout the nineteenth century had not for a moment reconciled itself with the loss of independence, and fighting for its own freedom, fought at the same time for the freedom of other nations.",
  "Life is made up, not of great sacrifices or duties, but of little things, in which smiles and kindness, and small obligations given habitually, are what preserve the heart and secure comfort.",
  "The Stones are a different kind of group. I realized that when I joined them. It's not really so much their musical ability, it's just they have a certain kind of style and attitude which is unique.",
  "The great art of films does not consist of descriptive movement of face and body but in the movements of thought and soul transmitted in a kind of intense isolation.",
  "Successful organizations, including the Military, have learned that the higher the risk, the more necessary it is to engage everyone's commitment and intelligence.",
  "One of the surest evidences of friendship that one individual can display to another is telling him gently of a fault. If any other can excel it, it is listening to such a disclosure with gratitude, and amending the error.",
  "Our subjective experience of time is highly variable. We all know that days can pass like weeks and months can feel like years, and that the opposite can be just as true: A month or year can zoom by in what feels like no time at all.",
  "The trite saying that honesty is the best policy has met with the just criticism that honesty is not policy. The real honest man is honest from conviction of what is right, not from policy.",
  "An educated person is one who has learned that information almost always turns out to be at best incomplete and very often false, misleading, fictitious, mendacious - just dead wrong.",
  "Heights by great men reached and kept were not obtained by sudden flight but, while their companions slept, they were toiling upward in the night.",
  "Buyers decide in the first eight seconds of seeing a home if they're interested in buying it. Get out of your car, walk in their shoes and see what they see within the first eight seconds.",
  "And I come here as a daughter, raised on the South Side of Chicago - by a father who was a blue-collar city worker and a mother who stayed at home with my brother and me.",
  "Anywhere you have extreme poverty and no national health insurance, no promise of health care regardless of social standing, that's where you see the sharp limitations of market-based health care.",
  "Sometimes, when I'm alone, I put on six inch heels and wear nothing else and dance around in front of the mirror and do my little stripper dance.",
  "My dad said if you become a tennis professional just make sure you get into the top hundred, because you have to make a little bit of money. You make a living so you can pay your coaching and, you know, your travels.",
  "Memory is a great artist. For every man and for every woman it makes the recollection of his or her life a work of art and an unfaithful record.",
  "Public office is supposed to be a public trust. This is a clear sign of the rampant corruption at the highest levels of the Republican leadership.",
  "If we can't face death, we'll never overcome it. You have to look it straight in the eye. Then you can turn around and walk back out into the light.",
  "Like all parents, my husband and I just do the best we can, hold our breath and hope we've set aside enough money for our kid's therapy.",
  "Literature overtakes history, for literature gives you more than one life. It expands experience and opens new opportunities to readers.",
  "I feel like I am a real artist and I want to be able to feel what I am singing about. So when I sing, 'Leave (Get Out),' I have been through that. I think it is just a new generation, whether people are ready for it or not. Teenagers are dating.",
  "Funny things tend not to happen to me. I am not a natural comic. I need to think about things a lot before I can be even remotely amusing.",
  "It is up to African leaders to show their will and political courage in order to assure that this new pan-African institution becomes an efficient instrument and not a place for endless discussions.",
  "I think the driving thing was curiosity about the universe. That fascinated me. I didn't think anything about being famous or anything like that, I was just interested in the concepts involved.",
  "My father was Catholic, my mother was Protestant, and because of that I got Christened in both churches, so I've got all these names... but my Dad always called me Mick.",
  "I think it's good that I had some experience of the real world before I became successful. You know, having to get up in the morning and going to work in construction.",
  "I read murder mysteries. I exercise 40 minutes a day. I watch videotapes while I exercise. I listen to audiotapes when I am in my car. And I try to stay in three different centuries.",
  "The guy who knows about computers is the last person you want to have creating documentation for people who don't understand computers.",
  "It's the beauty and curse of doing a daily show. Some days you've got nothing to talk about and other days Dick Cheney shoots his lawyer in the face and everyone is happy.",
  "If there is not the war, you don't get the great general if there is not a great occasion, you don't get a great statesman if Lincoln had lived in a time of peace, no one would have known his name.",
  "But baseball bounced back in the next decade to reclaim its place as the national pastime: new heroes, spirited competition, and booming prosperity gave birth to dreams of expansion, both within the major leagues and around the world.",
  "In a civilized society, all crimes are likely to be sins, but most sins are not and ought not to be treated as crimes. Man's ultimate responsibility is to God alone.",
  "Today, it is research with human embryonic stem cells and attempts to prepare cloned stem cells for research and medical therapies that are being disavowed as being ethically unacceptable.",
  "A growing number of young women who have the freedom to decide have decided that career can wait, and the delicious early years of their children's lives can't.",
  "Just as the science and art of agriculture depend upon chemistry and botany, so the art of education depends upon physiology and psychology.",
  "We have been learning since we were children how to make money, buy things, build things. The whole education system is set up to teach us how to think, not to feel.",
  "It was one of the most exciting, perfect evenings of my life, my solo debut at Carnegie Hall. And knowing we were all there to raise money for Gay Men's Health Crisis made the evening an extraordinary experience.",
  "We also maintain - again with perfect truth - that mystery is more than half of beauty, the element of strangeness that stirs the senses through the imagination.",
  "Like a lot of you, I grew up in a family on the ragged edges of the middle class. My daddy sold carpeting and ended up as a maintenance man. After he had a heart attack, my mom worked the phones at Sears so we could hang on to our house.",
  "One definition of eternity is that we are not alone on this planet, that there are those who've gone before and those who will come, and that there is a community of spirits.",
  "Everybody, even me, sometimes had to compromise on something, doing things we know to be wrong, and this happens doing whatever job in the world. But a singer must have the courage of saying no.",
  "The improvement of understanding is for two ends: first, our own increase of knowledge secondly, to enable us to deliver that knowledge to others.",
  "I have several computer companies. One of them I have a program for wide-format printing. I have a beauty program. So I have several different programs that I own for printing.",
  "I find that people find a way out of misery through humor and it's humor that's often unacceptable to people who are not in quite such a state of misery.",
  "I hope everybody's had fun, because I've enjoyed my ride. I can tell you that. Now it's time to step aside and let some other young kid come in and win. Hopefully, they will, too.",
  "Pick the day. Enjoy it - to the hilt. The day as it comes. People as they come... The past, I think, has helped me appreciate the present - and I don't want to spoil any of it by fretting about the future.",
  "The stones themselves are thick with history, and those cats that dash through the alleyways must surely be the ghosts of the famous dead in feline disguise.",
  "He's a guy's guy, so it pretty much became like the impressions - don't imitate Sean Connery's voice, and things like that. We were all kind of doing it towards the end of the film, anyway, and he was cool with it.",
  "But the person who scored well on an SAT will not necessarily be the best doctor or the best lawyer or the best businessman. These tests do not measure character, leadership, creativity, perseverance.",
  "In America, we no longer have an institutionalized, organized way of calling business to task - of taking them to account for what they've done - and this is especially true in the cultural realm.",
  "Look at growth, look at how much time people spend on the Net and look at the variety of things that they are doing. It's all really good, so I am actually encouraged by the fundamentals that underlie usage growth on the Net.",
  "God isn't compatible with machinery and scientific medicine and universal happiness. You must make your choice. Our civilization has chosen machinery and medicine and happiness.",
  "I do a lot of curiosity buying I buy it if I like the album cover, I buy it if I like the name of the band, anything that sparks my imagination.",
  "When I travel I normally eat club sandwiches or I bring my own food. When you go into a new town, it's very had to find a good place to eat.",
  "I was horrible at science and math. I couldn't pass a test to save my life! I'm surprised that it didn't take me until I was 20 to graduate. That's why my role is so cool - Grissom is the complete opposite of me.",
  "I have a Christian worldview and so it shapes the way that I view issues. I don't apologize for that, and I don't think people of faith ought to shrink away from being in the public arena.",
  "Great dad. Yeah, he would ask me for money on birthdays and, you know, inappropriate times. And I just wrote him off like, 'You're not a father.' I just learned you cannot emotionally invest in people who are not attainable.",
  "Perhaps religious conscience upsets the designs of those who feel that the highest wisdom and authority comes from government. But from the beginning, this nation trusted in God, not man. Religious liberty is the first freedom in our Constitution.",
  "Anyone can support a team that is winning - it takes no courage. But to stand behind a team to defend a team when it is down and really needs you, that takes a lot of courage.",
  "Our government is founded upon the intelligence of the people. I for one do not despair of the republic. I have great confidence in the virtue of the great majority of the people, and I cannot fear the result.",
  "Everybody past a certain age, regardless of how they look on the outside, pretty much constantly dreams of being able to escape from their lives.",
  "I think writing really helps you heal yourself. I think if you write long enough, you will be a healthy person. That is, if you write what you need to write, as opposed to what will make money, or what will make fame.",
  "You have people come into your life shockingly and surprisingly. You have losses that you never thought you'd experience. You have rejection and you have learn how to deal with that and how to get up the next day and go on with it.",
  "To do what we are doing in this budget to our children, cutting their health care funds, decreasing opportunity, simply so we can pay for tax cuts and a war in Iraq is beyond belief, and we need to reverse it.",
  "Thoughts will change and shift just like the wind and the water when you're on the boat thoughts are no different than anything else.",
  "If it's true that our species is alone in the universe, then I'd have to say the universe aimed rather low and settled for very little.",
  "But thankfully, my first album, 'Wide Screen,' was sort of a critics' darling - everyone raved about it, but no one bought it. They only manufactured 10,000 copies I wasn't even in the running for failure!",
  "The boundaries which divide Life from Death are at best shadowy and vague. Who shall say where the one ends, and where the other begins?",
  "A pregnant woman facing the most dire circumstances must be able to count on her doctor to do what is medically necessary to protect her from serious physical harm.",
  "I think that if you keep your eyes and your ears open and you are receptive to learning, there are skills you can get from any job at all.",
  "Here is the amazing thing about Easter the Resurrection Sunday for Christians is this, that Christ in the dying moments on the cross gives us the greatest illustration of forgiveness possible.",
  "I wrote a screenplay for a 'Sweet Valley High' adaptation, and it's really amazing to me how many women who are my age have responded to the idea and are excited about the movie.",
  "Most of the top actors and actresses may be working in ten or twelve films at the same time, so they will give one director two hours and maybe shoot in Bombay in the morning and Madras in the evening. It happens.",
  "Just two weeks ago, millions of Iraqis defied the threats of terrorists and went to the polls to determine their own future. I congratulate the Iraqi people for the courage they've shown in making these elections so successful.",
  "If you are a great dramatic actor then you often don't know if people are enjoying your stuff at all because they are sitting there in silence. But with comedy it's a simple premise. If it's funny, people laugh. If it's not, they don't.",
  "Generalised anger and frustration is something that gets you in the studio, and gets you to work - though it's not necessarily evident in anything that's finished.",
  "Music is an art that expresses the inexpressible. It rises far above what words can mean or the intelligence define. Its domain is the imponderable and impalpable land of the unconscious.",
  "Government's view of the economy could be summed up in a few short phrases: If it moves, tax it. If it keeps moving, regulate it. And if it stops moving, subsidize it.",
  "You control your future, your destiny. What you think about comes about. By recording your dreams and goals on paper, you set in motion the process of becoming the person you most want to be. Put your future in good hands - your own.",
  "I use to watch like maybe three or four movies, five days out of the week. I was a movie buff, but I really didn't know what it was like behind the scenes, or the whole political process of it.",
  "My parents got married late and they had kids late, so I never felt a social or cultural thing to be married or pregnant or a homeowner by a certain age.",
  "I don't really plan to be a pop star I just want to be able to make music without the whole My Dad thing hanging over me, which everyone in my position goes through.",
  "In Torch Song, I did that character almost non-stop from 1978 until I made the movie in 1987. Then I had some failure, which also colors how you react to doing other things.",
  "May it not be that, just as we have to have faith in Him, God has to have faith in us and, considering the history of the human race so far, may it not be that 'faith' is even more difficult for Him than it is for us?",
  "It's painful for me to watch someone who isn't funny. It's horrifying to sit in the back and watch some guy who just totally sucks.",
  "From about eight years old I was always making things on the sewing machine. Friends would see me making dresses and costumes, and I'd use difficult fabrics such as Lycra and elastic. But you know, my dad was creative and my brother is inventive too.",
  "The introduction of many minds into many fields of learning along a broad spectrum keeps alive questions about the accessibility, if not the unity, of knowledge.",
  "We need transparency in government spending. We need to put each government expenditure online so every Floridian can see where their tax money is being spent.",
  "Bruce Lee was very famous. I watched his movies and he is amazing. He is a martial arts master, his philosophy, his movement, both physically and mentally, were very strong.",
  "History offers no evidence for the proposition that the assignment of women to military combat jobs is the way to win wars, improve combat readiness, or promote national security.",
  "It's good to experience Hollywood in short bursts, I guess. Little snippets. I don't think I can handle being here all the time, it's pretty nutty.",
  "There must be room for the imagination to exercise its powers we must conceive and apprehend a thousand things which we do not actually witness.",
  "The faults of a superior person are like the sun and moon. They have their faults, and everyone sees them they change and everyone looks up to them.",
  "The terror of the atom age is not the violence of the new power but the speed of man's adjustment to it, the speed of his acceptance.",
  "The truth is that we can learn to condition our minds, bodies, and emotions to link pain or pleasure to whatever we choose. By changing what we link pain and pleasure to, we will instantly change our behaviors.",
  "A library, to modify the famous metaphor of Socrates, should be the delivery room for the birth of ideas - a place where history comes to life.",
  "The challenge is not to replace Obama but with who. It's not enough to just change up the uniform, if we don't change the team and the game plan, we won't save our country.",
  "In our civilization, and under our republican form of government, intelligence is so highly honored that it is rewarded by exemption from the cares of office.",
  "I'm set to have my best year ever: I'm hiring some acts and there will be a show in the morning, in the afternoon and in the evening. I'm going to use my theater to its fullest potential.",
  "It's a funny thing because you look at the careers of other filmmakers, and you see them sort of slow down, and you realize, maybe this becomes harder to do as you get older. That's sort of a cautionary thing. I hope it doesn't happen to me.",
  "If the events of September 11, 2001, have proven anything, it's that the terrorists can attack us, but they can't take away what makes us American - our freedom, our liberty, our civil rights. No, only Attorney General John Ashcroft can do that.",
  "You're creating an intimacy that everybody feels, that it's their experience, not yours. I'll never introduce a song and say, now this song is about 'my' broken heart.",
  "We must take action now, by permitting re-importation, to ensure that health care and prescription drugs remain accessible and affordable for everyone.",
  "When I left 20th Century-Fox to freelance, my agent believed that getting big money was the way to establish real importance in our industry.",
  "No one ever pretended that shopping for anything is a rational experience. If it were, would there be Fluffernutter? Laceless sneakers? Porkpie hats? Would the Chia Pet even exist?",
  "I used to be good with kids, but as I get older, I'm grumpy and terrible with them. As for doing a gig at a 6-year old's birthday party, you couldn't pay me enough.",
  "But, you know, they don't enjoy the dinner hour together. It's just not as much of a ritual at night and it's interesting. I think the ritual is taking place perhaps more in the morning.",
  "Open markets offer the only realistic hope of pulling billions of people in developing countries out of abject poverty, while sustaining prosperity in the industrialized world.",
  "My dad was always such a frustrated artist. He always worked very hard to support his family, doing a bunch of ridiculous jobs. He wanted to be a painter, but then he also wrote science-fiction novels in his spare time.",
  "My formula for living is quite simple. I get up in the morning and I go to bed at night. In between, I occupy myself as best I can.",
  "Precepts or maxims are of great weight and a few useful ones on hand do more to produce a happy life than the volumes we can't find.",
  "I told the brethren that the Book of Mormon was the most correct of any book on earth, and the keystone of our religion, and a man would get nearer to God by abiding by its precepts, than by any other book.",
  "The simplest questions are the most profound. Where were you born? Where is your home? Where are you going? What are you doing? Think about these once in a while and watch your answers change.",
  "Old age realizes the dreams of youth: look at Dean Swift in his youth he built an asylum for the insane, in his old age he was himself an inmate.",
  "The American attitude is 'We're the best'. That's why the NBA guys who come from other countries, the Europeans, all sort of stick together away from the game.",
  "The courts cannot garnish a father's salary, nor freeze his account, nor seize his property on behalf of his children, in our society. Apparently this is because a kid is not a car or a couch or a boat.",
  "Rock 'n' roll is ridiculous. It's absurd. In the past, U2 was trying to duck that. Now we're wrapping our arms around it and giving it a great big kiss.",
  "Being a mom's so empowering and incredible. I'm one of those people who believes that life brings things to you at a certain time for a certain reason, and if you just go with it, that's where the best moments come from.",
  "In just the same way the thousands of successive positions of a runner are contracted into one sole symbolic attitude, which our eye perceives, which art reproduces, and which becomes for everyone the image of a man who runs.",
  "I wanted to be a 150% entrepreneur and a 150% mom, and I found that I was having a very hard time doing both. I was about 75% and 75% - still better than 100%, but not what I was accustomed to at work.",
  "I think there's a lot of work to be done with our societies. My biggest passions are the environment and health. And when I say 'health' I mean the secrets behind health and our food system.",
  "Life is the fire that burns and the sun that gives light. Life is the wind and the rain and the thunder in the sky. Life is matter and is earth, what is and what is not, and what beyond is in Eternity.",
  "But the mechanics of learning to 'throw your voice' are pretty simple. Anyone with a tongue, an upper palate, teeth, and a normal speaking voice can learn ventriloquism.",
  "It is not difficult for me to have this faith, for it is incontrovertible that where there is a plan there is intelligence - an orderly, unfolding universe testifies to the truth of the most majestic statement ever uttered - 'In the beginning, God.'",
  "My background was computer science and business school, so eventually I worked my way up where I was running product groups - development, testing, marketing, user education.",
  "When I come home and I'm tired from filming all day, I expect her to be there and make sure everything is cool for me. You know, like drawing my bath and helping me into bed.",
  "I've traveled all over the country for years speaking in churches, teaching the Ten Commandments. It's amazing if 2 percent of any congregation knows the Ten Commandments.",
  "My father probably thought the capital of the world was wherever he was at the time. It couldn't possibly be anyplace else. Where he and his wife were in their own home, that, for them, was the capital of the world.",
  "Directing is: you're overwhelmed the whole time. Your mind never stops. If you care about it. You wake up in the morning and you begin thinking about it and then you go to sleep at night and you're still thinking about it.",
  "I've always felt that sexuality is a really slippery thing. In this day and age, it tends to get categorized and labeled, and I think labels are for food. Canned food.",
  "I loved hip-hop. The first stuff I heard was Public Enemy, and I couldn't believe it. It was amazing, and I've always loved hip-hop.",
  "Feeling is the consciousness of the resulting conditions - of success, failure, equilibrium, compromise or balance, in this continuous rivalry of ideas.",
  "And while the law of competition may be sometimes hard for the individual, it is best for the race, because it ensures the survival of the fittest in every department.",
  "The word 'good' has many meanings. For example, if a man were to shoot his grandmother at a range of five hundred yards, I should call him a good shot, but not necessarily a good man.",
  "Leadership is an active role 'lead' is a verb. But the leader who tries to do it all is headed for burnout, and in a powerful hurry.",
  "If there's specific resistance to women making movies, I just choose to ignore that as an obstacle for two reasons: I can't change my gender, and I refuse to stop making movies.",
  "Man is born in a day, and he dies in a day, and the thing is easily over but to have a sick heart for three-fourths of one's lifetime is simply to have death renewed every morning and life at that price is not worth living.",
  "A live concert to me is exciting because of all the electricity that is generated in the crowd and on stage. It's my favorite part of the business, live concerts.",
  "The most important thing is the indigenous people are not vindictive by nature. We are not here to oppress anybody - but to join together and build Bolivia, with justice and equality.",
  "The failure of the United Nations - My failure is maybe, in retrospective, that I was not enough aggressive with the members of the Security Council.",
  "But the person who scored well on an SAT will not necessarily be the best doctor or the best lawyer or the best businessman. These tests do not measure character, leadership, creativity, perseverance.",
  "A cardinal principle of Total Quality escapes too many managers: you cannot continuously improve interdependent systems and processes until you progressively perfect interdependent, interpersonal relationships.",
  "Reputation is favorable notoriety as distinguished from fame, which is permanent approval of great deeds and noble thoughts by the best intelligence of mankind.",
  "Christians must share their faith in obedience to the Great Commission, because we are only seeing the fruit of sin this side of death.",
  "Global markets must be balanced by global values such as respect for human rights and international law, democracy, security and sustainable economic and environmental development.",
  "When I was doing ensemble theater and comedy work, I felt I had some talents. But when I started doing my shows in Berkeley and found that I could be funny on my own, I was shocked.",
  "We're reclaiming America and restoring honor. I believe we do that with faith, with hope, with charity, and honoring our brothers and our sisters as we honor each other.",
  "It was my father who taught me to value myself. He told me that I was uncommonly beautiful and that I was the most precious thing in his life.",
  "A member must say that he is a member of the Unification Church and that he is the follower of Sun Myung Moon. If he doesn't have the courage to say it, he is not worthy of me.",
  "Boxing is my real passion. I can go to ballet, theatre, movies, or other sporting events... and nothing is like the fights to me. I'm excited by the visual beauty of it. A boxer can look so spectacular by doing a good job.",
  "It is an open question whether any behavior based on fear of eternal punishment can be regarded as ethical or should be regarded as merely cowardly.",
  "You want to shut up every Negro who has the courage to stand up and fight for the rights of his people, for the rights of workers, and I have been on many a picket line for the steelworkers too.",
  "The savior who wants to turn men into angels is as much a hater of human nature as the totalitarian despot who wants to turn them into puppets.",
  "Consular cards were not designed to be identification and no treaty recognizes them as such. Legal travelers, visitors and long-term residents carried passports, visas or green cards for that purpose.",
  "I find, by experience, that the mind and the body are more than married, for they are most intimately united and when one suffers, the other sympathizes.",
  "Contrary to current cynicism about past golden ages, the abstraction known as 'the intelligent layperson' does exist - in the form of millions of folks with a passionate commitment to continuous learning.",
  "I'm so intrigued by women throughout history where the significance of what they were representing at that time is obscured by the fact a man saved them or they were prostitutes.",
  "In a mood of faith and hope my work goes on. A ream of fresh paper lies on my desk waiting for the next book. I am a writer and I take up my pen to write.",
  "In November, they transferred control of Abu Ghraib to the military intelligence command completely it was, after all, the center for interrogations for Iraq.",
  "You will be a failure, until you impress the subconscious with the conviction you are a success. This is done by making an affirmation which 'clicks.'",
  "My mom had this romantic notion of her children playing classical music. The idea is you learn it when you're still learning language. It's using the same part of the brain.",
  "Morality and its victim, the mother - what a terrible picture! Is there indeed anything more terrible, more criminal, than our glorified sacred function of motherhood?",
  "Sinful and forbidden pleasures are like poisoned bread they may satisfy appetite for the moment, but there is death in them at the end.",
  "As a small business owner for the last 15 years, when I think of what truly changed my life, it was my faith, a strong family, my mom did a really, really good job of encouraging me in very clear and discernible ways.",
  "Be courageous. I have seen many depressions in business. Always America has emerged from these stronger and more prosperous. Be brave as your fathers before you. Have faith! Go forward!",
  "Forgiveness is the answer to the child's dream of a miracle by which what is broken is made whole again, what is soiled is made clean again.",
  "The waste of capital, in proportion to the total capital, in this country between 1800 and 1850, in the attempts which were made to establish means of communication and transportation, was enormous.",
  "You know, if you are kind of rich, the best thing is that you don't have to think about money. The best thing you can buy with money is freedom, time. I don't know how much I earn a year. I have no idea. I don't know how much I pay in taxes.",
  "I had decided I wanted to write about food, and I knew the only way to do that is to speak with authority, which meant learning the language and knowing what that experience is like.",
  "The bottom line is, I'm blessed with good health. On top of that, I don't go around thinking 'Oh, I'm 90, I better do this or I better do that.' I'm just Betty. I'm the same Betty that I've always been. Take it or leave it.",
  "We must guard against the overreaching hand of big government trying to take away our freedom. And we must always protect the environment in a manner consistent with our values.",
  "When I was growing up in New Jersey, my mom would regularly take my sister and I into the city to see shows. I have many fond memories of standing in the half-price ticket line in Times Square and going to matinees.",
  "We should be dreaming. We grew up as kids having dreams, but now we're too sophisticated as adults, as a nation. We stopped dreaming. We should always have dreams.",
  "And though various organizations in America and England collected money and sent food parcels to these refugees, nothing was ever received by the Spanish.",
  "Look, architecture has a lot of places to hide behind, a lot of excuses. 'The client made me do this.' 'The city made me do this.' 'Oh, the budget.' I don't believe that anymore.",
  "What we call wisdom is the result of all the wisdom of past ages. Our best institutions are like young trees growing upon the roots of the old trunks that have crumbled away.",
  "I find happiness comes from numerous sources in my life. Most often, the happy moments I cherish most are quiet moments with my wife and family back home in Nova Scotia.",
  "Judgments, value judgments concerning life, for or against, can in the last resort never be true: they possess value only as symptoms, they come into consideration only as symptoms - in themselves such judgments are stupidities.",
  "I remember a great America where we made everything. There was a time when the only thing you got from Japan was a really bad cheap transistor radio that some aunt gave you for Christmas.",
  "When two people first meet, they can only have a very ordinary kind of friendship. But when you begin to understand each other, when you get close to them, you discover that you're suddenly eager to know him or her even better.",
  "I took the initiative in moving forward a whole range of initiatives that have proven to be important to our country's economic growth, environmental protection, improvements in our educational system.",
  "When I speak of the beauty of a game of chess, then naturally this is subjective. Beauty can be found in a very technical, mathematical game for example. That is the beauty of clarity.",
  "If you dream of something worth doing and then simply go to work on it and don't think anything of personalities, or emotional conflicts, or of money, or of family distractions it is amazing how quickly you get through those 5,000 steps.",
  "In working with UNICEF our corporate partners have demonstrated time and again that their financial resources, leadership and expertise can bring about real and lasting benefits for the world's children.",
  "I noticed that this defense attorney is a very, very intelligent man, and he's very cool and he's very knowledgeable, and I think that personally I'd like to have an attorney like him.",
  "I get up early in the morning, 4 o'clock, and I sit at my desk and what I do is just dream. After three or four hours, that's enough. In the afternoon, I run.",
  "Outside museums, in noisy public squares, people look at people. Inside museums, we leave that realm and enter what might be called the group-mind, getting quiet to look at art.",
  "A guy is a lump like a doughnut. So, first you gotta get rid of all the stuff his mom did to him. And then you gotta get rid of all that macho crap that they pick up from beer commercials. And then there's my personal favorite, the male ego.",
  "I do resent that when you're in the most cool, powerful time of your life, which is your 40s, you're put out to pasture. I think women are so much cooler when they're older. So it's a drag that we're not allowed to age.",
  "When I was born in 1970 with a rare genetic disorder called spondyloepiphyseal dysplasia congenita (SED), medical science wasn't what it is today and my mum and dad were treated terribly by the medical profession.",
  "Fix reason firmly in her seat, and call to her tribunal every fact, every opinion. Question with boldness even the existence of a God because, if there be one, he must more approve of the homage of reason, than that of blindfolded fear.",
  "The superior man is distressed by the limitations of his ability he is not distressed by the fact that men do not recognize the ability that he has.",
  "I think we have to face the reality that in a society where there is a legitimate threat of terrorism, not being able to see one's face, not being able to have some sense of communication in that way, is for many societies a challenge.",
  "The president has declared that the debate over government-controlled health care is over. That will come as news to the millions of Americans who will elect Mitt Romney so we can repeal Obamacare.",
  "The traditional Christian attitude toward human personality was that human nature was essentially good and that it was formed and modified by social pressures and training.",
  "Our fathers had their dreams we have ours the generation that follows will have its own. Without dreams and phantoms man cannot exist.",
  "Well, it's a humor strip, so my first responsibility has always been to entertain the reader... But if, in addition, I can help move readers to thought and judgment about issues that concern me, so much the better.",
  "But the fact is, I'm not work-identified. I'm not a lawyer or a writer. I'm a mom, and I'm a woman, and that's the kind of people I want to see in books in the starring role.",
  "I think I turned to writing really just to wake up in the morning and be a musician and to have something to do, and feel like a musician every day even if I wasn't working.",
  "We in the United States should be all the more thankful for the freedom and religious tolerance we enjoy. And we should always remember the lessons learned from the Holocaust, in hopes we stay vigilant against such inhumanity now and in the future.",
  "We may need to change the way we think. As in Israel, I think there should be a mandatory draft, where you go away for the service of your country for three years.",
  "The history of our country is cruel. We have to face those issues or, should I say, we had to. Not anymore I hope, because we are going in the right direction, and we are ready to forgive, ready to move on.",
  "Doubt is an uneasy and dissatisfied state from which we struggle to free ourselves and pass into the state of belief while the latter is a calm and satisfactory state which we do not wish to avoid, or to change to a belief in anything else.",
  "Holding on to anger, resentment and hurt only gives you tense muscles, a headache and a sore jaw from clenching your teeth. Forgiveness gives you back the laughter and the lightness in your life.",
  "My overcoat is worn out my shirts also are worn out. And I ask to be allowed to have a lamp in the evening it is indeed wearisome sitting alone in the dark.",
  "I left science, then I went into art, but I approach things very analytically. I choose to pursue both art and architecture as completely separate fields rather than merging them.",
  "I did 10 years of comedies and 10 years of Westerns. I really like to stay away from car chases. I prefer the more intimate film. You have a much more direct association with the emotions.",
  "Usually a family is led through the mom or the dad and their career and for the family to be led by my career, even though God has led it, could be a lot of pressure.",
  "Originally created to serve the poorest and sickest among us, the Medicaid program has grown dramatically but still doesn't include the kind of flexibility that states need to provide better health care for the poor and disadvantaged.",
  "I have this idealistic and maybe naive thought that almost any song can be anything. If you record one song today, it would maybe be exciting and cool. But I could record the same song next week and it would be something completely different.",
  "Newspaper people, once celebrated as founts of ribald humor and uncouth fun, have of late lost all their gaiety, and small wonder.",
  "I've always been an avid reader. If I don't have a book in the car, I'll stop and pick one up just to have something to read. I don't even remember learning to read.",
  "In its famous paradox, the equation of money and excrement, psychoanalysis becomes the first science to state what common sense and the poets have long known - that the essence of money is in its absolute worthlessness.",
  "Contaminated food is a major cause of diarrhea, substantially contributing to malnutrition and killing about 2.2 million people each year, most of them children.",
  "Since the reduction of risk factors is the scientific basis for primary prevention, the World Health Organization promotes the development of an integrated strategy for prevention of several diseases, rather than focusing on individual ones.",
  "I know of nothing more despicable and pathetic than a man who devotes all the hours of the waking day to the making of money for money's sake.",
  "Few women, I fear, have had such reason as I have to think the long sad years of youth were worth living for the sake of middle age.",
  "The only faith that wears well and holds its color in all weathers is that which is woven of conviction and set with the sharp mordant of experience.",
  "Here's the funny thing about the response I've been aware of to my dating famous people: It's been very negative. I'm either not good-looking enough, not a good enough actor or not successful enough for these people.",
  "The death of any man aged 56 is very sad for his widow and family. And no one would deny that Steve Jobs was a brilliant and highly innovative technician, with great business flair and marketing ability.",
  "War alone brings up to their highest tension all human energies and imposes the stamp of nobility upon the peoples who have the courage to make it.",
  "Grades were important in our house. I was reading by two. My mom would sit there and read with me, read with me, read with me. It was wonderful.",
  "There is an opportunity for us to renew ourselves. There's an opportunity for us to leave the past behind and present something different for the future.",
  "I'd like to design something like a city or a museum. I want to do something hands on rather than just play golf which is the sport of the religious right.",
  "I am a particular fan of integrative exercise - that is, exercise that occurs in the course of doing some productive activity such as gardening, bicycling to work, doing home improvement projects and so on.",
  "We cannot remember too often that when we observe nature, and especially the ordering of nature, it is always ourselves alone we are observing.",
  "The unproductive tillage of human cattle takes that which of right belongs to free labor, and which is necessary for the support and happiness of our own race.",
  "I left science, then I went into art, but I approach things very analytically. I choose to pursue both art and architecture as completely separate fields rather than merging them.",
  "My general attitude to life is to enjoy every minute of every day. I never do anything with a feeling of, 'Oh God, I've got to do this today.'",
  "This generation... they have a different attitude. Instead of sitting and watching something, they want to be a part of it - they're very hedonistic and sensual.",
  "I think there's a lot of work to be done with our societies. My biggest passions are the environment and health. And when I say 'health' I mean the secrets behind health and our food system.",
  "The stones themselves are thick with history, and those cats that dash through the alleyways must surely be the ghosts of the famous dead in feline disguise.",
  "As long as the opposition believes the world will stand with Ukraine's democrat reformers, they will have the leverage and the courage to establish a legitimate republic under the leadership of Viktor Yushchenko.",
  "I think there is a big difference between expressing the pain and anger that many African Americans and other people of color may feel versus language that I think now crosses the line and goes into hate.",
  "I worry whether it's not really the best way to live one's life - trying to fulfill the dreams you had as a child. Maybe it's quite a backwards approach.",
  "Reading isn't good for a ballplayer. Not good for his eyes. If my eyes went bad even a little bit I couldn't hit home runs. So I gave up reading.",
  "I'm an immigrant kid who came to America from India when I was very young and grew up in New York City with a single mom and really was influenced by all of those immigrant cultures bumping up against each other.",
  "I know acts and I'm not going to name names but these people sold ten million copies the first time and the second album sells three million and it's considered a failure and they're dropped and that's really a shame.",
  "We know that communication must be hampered, and its form largely determined, by the unconscious but inevitable influence of a transmitting mechanism, whether that be of a merely mechanical or of a physiological character.",
  "When I was younger it was - you know, my dad dressed up in drag on 'Bosom Buddies.' And that was what I was having to deal with at the time. And then around the time that I was into college was when he became statue-worthy I guess you could say.",
  "When you put gas in your car you are making a political statement, because you are supporting the empires that control and continue the destruction of some countries.",
  "I was very much into buying contemporary art, but I've just decided I want to get rid of it all. Not that it's not great art, but all of a sudden my mood has changed, and I want to go back to seventeenth- and eighteenth-century masters.",
  "After I set out to refute Christianity intellectually and couldn't, I came to the conclusion the Bible was true and Jesus Christ was God's Son.",
  "No matter how corrupt and unjust a convict may be, he loves fairness more than anything else. If the people placed over him are unfair, from year to year he lapses into an embittered state characterized by an extreme lack of faith.",
  "I was into all kinds of music as a teen - country music, because my dad was in a band that played country, and whatever my sister and brother were into.",
  "I had used eclectic therapy and behavior therapy on myself at the age of 19 to get over my fear of public speaking and of approaching young women in public.",
  "I pray to be a good servant to God, a father, a husband, a son, a friend, a brother, an uncle, a good neighbor, a good leader to those who look up to me, a good follower to those who are serving God and doing the right thing.",
  "There are going to be little victories that we claim, even if it's finishing 15th and putting the car back in hauler without a scratch on it.",
  "As long as the food is well prepared and not overdone, I think it tastes good. It doesn't matter if it's Chinese, Japanese, anything.",
  "Cure yourself of the affliction of caring how you appear to others. Concern yourself only with how you appear before God, concern yourself only with the idea that God may have of you.",
  "There really are three types of 'religious' movies: the ones that make fun of it, the ones that vilify it and the ones that literally preach to the converted.",
  "One of the great attractions of patriotism - it fulfills our worst wishes. In the person of our nation we are able, vicariously, to bully and cheat. Bully and cheat, what's more, with a feeling that we are profoundly virtuous.",
  "Your ability to communicate is an important tool in your pursuit of your goals, whether it is with your family, your co-workers or your clients and customers.",
  "There is a bright spot or two for the Spaniards. French toast has become freedom toast on the Air Force One breakfast menu, but the Spanish omelet is still a Spanish omelet.",
  "Bullfighting is the only art in which the artist is in danger of death and in which the degree of brilliance in the performance is left to the fighter's honor.",
  "The highest and most beautiful things in life are not to be heard about, nor read about, nor seen but, if one will, are to be lived.",
  "When I was growing up in Mississippi - it was good Southern food... but I also grew up with a Greek family when other kids were eating fried okra, we were eating steamed artichokes. So I think it played a big part in my healthy cooking.",
  "Bad religion is arrogant, self-righteous, dogmatic and intolerant. And so is bad science. But unlike religious fundamentalists, scientific fundamentalists do not realize that their opinions are based on faith. They think they know the truth.",
  "We need to reclaim our American system of limited government, low taxes, reasonable regulations, and sound money, which has blessed us with unprecedented prosperity. And it has done more to help the poor than any other economic system ever designed.",
  "I have six locks on my door all in a row. When I go out, I lock every other one. I figure no matter how long somebody stands there picking the locks, they are always locking three.",
  "You want to believe that there's one relationship in life that's beyond betrayal. A relationship that's beyond that kind of hurt. And there isn't.",
  "The moment we begin to fear the opinions of others and hesitate to tell the truth that is in us, and from motives of policy are silent when we should speak, the divine floods of light and life no longer flow into our souls.",
  "I can do comedy, so people want me to do that, but the other side of comedy is depression. Deep, deep depression is the flip side of comedy. Casting agents don't realize it but in order to be funny you have to have that other side.",
  "Procedures outside the stadiums and in the parking areas still need to be optimized, for example so that emergency medical services can leave the grounds on their way to the hospital faster.",
  "Art must unquestionably have a social value that is, as a potential means of communication it must be addressed, and in comprehensible terms, to the understanding of mankind.",
  "And now the momentous day, a day to be forever remembered in the annals of the country, arrived. Early in the morning on the 1st of July the conflict began.",
  "An invincible determination can accomplish almost anything and in this lies the great distinction between great men and little men.",
  "Why do you think the old stories tell of men who set out on great journeys to impress the gods? Because trying to impress people just isn't worth the time and effort.",
  "We're all entitled to opinions about how art institutions should behave, and entitled to voicing those opinions through whatever means available to us. We're also allowed to change or modify our opinions.",
  "I think, at a child's birth, if a mother could ask a fairy godmother to endow it with the most useful gift, that gift should be curiosity.",
  "Behind every small business, there's a story worth knowing. All the corner shops in our towns and cities, the restaurants, cleaners, gyms, hair salons, hardware stores - these didn't come out of nowhere.",
  "I've never held myself up particularly high when I had movies that worked, and I never held myself all that low when I had failures.",
  "If you improve a teacher's self-esteem, confidence, communication skills or stress levels, you improve that teacher's overall effectiveness across the curriculum.",
  "If you are going to achieve excellence in big things, you develop the habit in little matters. Excellence is not an exception, it is a prevailing attitude.",
  "Many people have the ambition to succeed in their work; they may even have special aptitude for their job. And yet they do not move ahead. Why? Perhaps they think that since they can master the job, there is no need to master themselves.",
  "Some of the reasons John McCain lost in 2008 were his lackluster campaign, his refusal to showcase Obama's extreme liberalism and, thus, his failure to demonstrate why he would make a better president than Obama.",
  "Let us take things as we find them: let us not attempt to distort them into what they are not... We cannot make facts. All our wishing cannot change them. We must use them.",
  "For a man to attain to an eminent degree in learning costs him time, watching, hunger, nakedness, dizziness in the head, weakness in the stomach, and other inconveniences.",
  "And in that I cannot send unto you all my businesses in writing, I despatch these present bearers fully informed in all things, to whom it may please you to give faith and credence in what they shall say unto you by word of mouth.",
  "If we ever start communicating with living creatures from other planets, the number one priority is, how are you going to communicate information? Even between different cultures here on Earth, you get into communication problems.",
  "Whole areas of knowledge and information have been defined into nonexistence because the system cannot know, understand, control, or measure them.",
  "I'd always been a news junkie, always read lots of newspapers and watched the Sunday morning news shows on TV and felt strongly about issues of power, control, sexuality and race.",
  "I am invariably late for appointments - sometimes as much as two hours. I've tried to change my ways but the things that make me late are too strong, and too pleasing.",
  "By a continuing process of inflation, government can confiscate, secretly and unobserved, an important part of the wealth of their citizens.",
  "The minute you try to talk business with him he takes the attitude that he is a gentleman and a scholar, and the moment you try to approach him on the level of his moral integrity he starts to talk business.",
  "You can close more business in two months by becoming interested in other people than you can in two years by trying to get people interested in you.",
  "Hit a home run - put your head down, drop the bat, run around the bases, because the name on the front is more - a lot more important than the name on the back.",
  "By helping readers understand these mechanics, I hope they will appreciate why freedom is for everyone, why it is essential for our security and why the free world plays a critically important role in advancing democracy around the globe.",
  "Unnecessary possessions are unnecessary burdens. If you have them, you have to take care of them! There is great freedom in simplicity of living. It is those who have enough but not too much who are the happiest.",
  "The man who comes up with a means for doing or producing almost anything better, faster or more economically has his future and his fortune at his fingertips.",
  "As Americans, we don't see the role of government as guaranteeing outcomes, but allowing free men and women to flourish based on their own vision, their hard work and their personal responsibility.",
  "The way that a handful of corporations in Los Angeles dictate how our stories are told creates a real poverty of imagination and it's a big problem.",
  "Men often oppose a thing merely because they have had no agency in planning it, or because it may have been planned by those whom they dislike.",
  "Education is the period during which you are being instructed by somebody you do not know, about something you do not want to know.",
  "I've made three musical movies which is pretty good considering that not many are made but I was lucky in other ways. I came along when independent movies were starting to boom.",
  "I believe that education is all about being excited about something. Seeing passion and enthusiasm helps push an educational message.",
  "I'd like to state that Spike Lee is not saying that African American culture is just for black people alone to enjoy and cherish. Culture is for everybody.",
  "Civilization is the progress toward a society of privacy. The savage's whole existence is public, ruled by the laws of his tribe. Civilization is the process of setting man free from men.",
  "Me and my dad are friends. We're cool. I'll never be disappointed again, because I don't expect anything anymore from him. I just let him exist, and that's how we get along.",
  "If I had to come up with something that just came to me, I think growing up in a small town, I want knowledge. I still think today, knowledge is one of the keys.",
  "It's a tremendous responsibility to be direct descendants of the prophet Muhammad. This family has had the burden of leadership on its shoulders for 1,400 years. I'm not going to drop the ball on my shift.",
  "Anything that isn't opposed by about 40 percent of humanity is either an evil business or so unimportant that it simply doesn't matter.",
  "Usually a family is led through the mom or the dad and their career and for the family to be led by my career, even though God has led it, could be a lot of pressure.",
  "I know there's some kind of history to mountain music-like it came from Ireland or England or Scotland and we kept up the tradition.",
  "In principle, there are only three main components of spending that much matter to monetary policy: consumer spending, business investment and exports and trade.",
  "You do things when the opportunities come along. I've had periods in my life when I've had a bundle of ideas come along, and I've had long dry spells. If I get an idea next week, I'll do something. If not, I won't do a damn thing.",
  "A commitment to sexual equality with males is a commitment to becoming the rich instead of the poor, the rapist instead of the raped, the murderer instead of the murdered.",
  "Mental illness can happen to anybody. You can be a dustman, a politician, a Tesco worker... anyone. It could be your dad, your brother or your aunt.",
  "It's funny how the hippies and the punks tried to get rid of the conservatives, but they always seem to get the upper hand in the end.",
  "But steel bars have never yet kept out a mob it takes something a good deal stronger: human courage backed up by the consciousness of being right.",
  "So the thing I realized rather gradually - I must say starting about 20 years ago now that we know about computers and things - there's a possibility of a more general basis for rules to describe nature.",
  "One thing about being successful is that I stopped being afraid of dying. Once you're a star you're dead already. You're embalmed.",
  "The left dismisses talk about the collapse of family life and talks instead about the emergence of the growing new diversity of family types.",
  "We are faced with the paradoxical fact that education has become one of the chief obstacles to intelligence and freedom of thought.",
  "The secret to success is good leadership, and good leadership is all about making the lives of your team members or workers better.",
  "It's your outlook on life that counts. If you take yourself lightly and don't take yourself too seriously, pretty soon you can find the humor in our everyday lives. And sometimes it can be a lifesaver.",
  "Building art is a synthesis of life in materialised form. We should try to bring in under the same hat not a splintered way of thinking, but all in harmony together.",
  "The South is very beautiful but its beauty makes one sad because the lives that people live here, and have lived here, are so ugly.",
  "I think that my vampires in general were influenced by my being allowed to watch the Hammer vampire films. Vampire Circus, also shown as Circus of Fear, was one of those movies.",
  "So nevertheless, what I'm saying is that what one is - one's parameters are constantly narrowed by one's success, and my desire is to widen my field even if I risk failure.",
  "If a star or studio chief or any other great movie personages find themselves sitting among a lot of nobodies, they get frightened - as if somebody was trying to demote them.",
  "Getting out of the hospital is a lot like resigning from a book club. You're not out of it until the computer says you're out of it.",
  "As a father now, I wouldn't do what my dad did, because it left me feeling emotionally unstable as a kid. But he didn't do the things he did out of selfishness or malice.",
  "Any work that's worth doing has its challenges as well as its opportunities. That's true if you're running a business, it's true if you're trying to help on a campaign.",
  "There aren't a lot of ironclad rules of family life, but here's one: No matter how much your parents deny it - and here's betting they deny it a lot - they have a favorite child. And if you're a parent, so do you.",
  "Often as a child you see someone with a learning disability or Down's Syndrome and my mum and dad were always very quick to explain exactly what was going on and to be in their own way inclusive and welcoming.",
  "When friendship disappears then there is a space left open to that awful loneliness of the outside world which is like the cold space between the planets. It is an air in which men perish utterly.",
  "I think it's impossible to judge whether another person should come out. You just hope they will on their own time and their own terms.",
  "As for gun control advocates, I have no hope whatever that any facts whatever will make the slightest dent in their thinking - or lack of thinking.",
  "Turkey wants a policy of engagement exactly like President Obama's new approach. Policy of engagement, less confrontation, less tense attitude, especially in the region.",
  "We have by far the most expensive health system in the world. We spend 50 percent more per person than the next most costly nation. Americans spend more on health care than housing or food.",
  "I think humor is a very serious thing. I use it as a way of weakening the reader's defenses so that I can more easily take him to something more.",
  "At the time when this famous historical battle was fought in Kosovo, the people were looking at the stars, expecting aid from them. Now, six centuries later, they are looking at the stars again, waiting to conquer them.",
];

const randomWords =
  "in one good real one not school set they state high life consider on and not come what also for set point can want as while with of order child about school thing never hold find order each too between program work end you home place around while place problem end begin interest while public or where see time those increase interest be give end think seem small as both another a child same eye you between way do who into again good fact than under very head become real possible some write know however late each that with because that place nation only for each change form consider we would interest with world so order or run more open that large write turn never over open each over change still old take hold need give by consider line only leave while what set up number part form want against great problem can because head so first this here would course become help year first end want both fact public long word down also long for without new turn against the because write seem line interest call not if line thing what work people way may old consider leave hold want life between most place may if go who need fact such program where which end off child down change to from people high during people find to however into small new general it do that could old for last get another hand much eye great no work and with but good there last think can around use like number never since world need what we around part show new come seem while some and since still small these you general which seem will place come order form how about just also they with state late use both early too lead general seem there point take general seem few out like might under if ask while such interest feel word right again how about system such between late want fact up problem stand new say move a lead small however large public out by eye here over so be way use like say people work for since interest so face order school good not most run problem group run she late other problem real form what just high no man do under would to each too end point give number child through so this large see get form also all those course to work during about he plan still so like down he look down where course at who plan way so since come against he all who at world because while so few last these mean take house who old way large no first too now off would in this course present order home public school back own little about he develop of do over help day house stand present another by few come that down last or use say take would each even govern play around back under some line think she even when from do real problem between long as there school do as mean to all on other good may from might call world thing life turn of he look last problem after get show want need thing old other during be again develop come from consider the now number say life interest to system only group world same state school one problem between for turn run at very against eye must go both still all a as so after play eye little be those should out after which these both much house become both school this he real and may mean time by real number other as feel at end ask plan come turn by all head increase he present increase use stand after see order lead than system here ask in of look point little too without each for both but right we come world much own set we right off long those stand go both but under now must real general then before with much those at no of we only back these person plan from run new as own take early just increase only look open follow get that on system the mean plan man over it possible if most late line would first without real hand say turn point small set at in system however to be home show new again come under because about show face child know person large program how over could thing from out world while nation stand part run have look what many system order some one program you great could write day do he any also where child late face eye run still again on by as call high the must by late little mean never another seem to leave because for day against public long number word about after much need open change also".split(
    " "
  );
function getRandomWords() {
  let arr = [];
  for (let i = 0; i < 32; i++) {
    let randomI = Math.floor(randomWords.length * Math.random());
    arr.push(randomWords[randomI]);
    if (i == 31) {
      randomI = Math.floor(randomWords.length * Math.random());
      arr.push(randomWords[randomI] + ".");
    }
  }
  return arr.join(" ");
}
function getQuote(level) {
  if (level === 0) {
    return getRandomWords();
  } else if (level === 1) {
    return quotes[Math.floor(Math.random() * quotes.length)];
  } else {
    return "something is wrong.";
  }
}
module.exports = { quotes, getRandomWords, getQuote };
